spring.application.name=helloworld
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/accounts}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:abuckingham}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=always