spring.application.name=helloworld
spring.datasource.url=jdbc:postgresql://localhost:5432/tasks_db
spring.datasource.username=abuckingham
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=never
